In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
data_path = '/product_marketing/06_customer_segmentation_demographics/netflix_users.csv'
netflix_user = pd.read_csv('netflix_users.csv')

In [8]:
netflix_user.head()

,User_ID,Name,Age,Country,Subscription_Type,Watch_Time_Hours,Favorite_Genre,Last_Login
0,1,James Martinez,18,France,Premium,80.26,Drama,2024-05-12
1,2,John Miller,23,USA,Premium,321.75,Sci-Fi,2025-02-05
2,3,Emma Davis,60,UK,Basic,35.89,Comedy,2025-01-24
3,4,Emma Miller,44,USA,Premium,261.56,Documentary,2024-03-25
4,5,Jane Smith,68,USA,Standard,909.30,Drama,2025-01-14

In [9]:
netflix_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   User_ID            25000 non-null  int64
 1   Name               25000 non-null  object
 2   Age                25000 non-null  int64
 3   Country            25000 non-null  object
 4   Subscription_Type  25000 non-null  object
 5   Watch_Time_Hours   25000 non-null  float64
 6   Favorite_Genre     25000 non-null  object
 7   Last_Login         25000 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 1.5+ MB

In [10]:
netflix_user.describe()

            User_ID           Age  Watch_Time_Hours
count  25000.000000  25000.000000      25000.000000
mean   12500.500000     46.482880        500.468858
std     7217.022701     19.594861        286.381815
min        1.000000     13.000000          0.120000
25%     6250.750000     29.000000        256.567500
50%    12500.500000     46.000000        501.505000
75%    18750.250000     63.000000        745.732500
max    25000.000000     80.000000        999.990000

In [14]:
# unique values in categorical columns
categorical_cols = ['Country', 'Subscription_Type', 'Favorite_Genre']
for col in categorical_cols:
    print(f"Unique values in {col}: {netflix_user[col].unique()}")

Unique values in Country: ['France' 'USA' 'UK' 'Canada' 'Mexico' 'Japan' 'Australia' 'Germany'
 'Brazil' 'India']
Unique values in Subscription_Type: ['Premium' 'Basic' 'Standard']
Unique values in Favorite_Genre: ['Drama' 'Sci-Fi' 'Comedy' 'Documentary' 'Romance' 'Action' 'Horror']